package com.nbc.nbcprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Global Clearance Number")
	private java.lang.String globalClearenceNumber;
	@org.kie.api.definition.type.Label("EShare Number")
	private java.lang.String eShareNumber;
	@org.kie.api.definition.type.Label("Agreement Type")
	private java.lang.String agreement_type;
	@org.kie.api.definition.type.Label("Budget Requested")
	private Float budget_requested;

	@org.kie.api.definition.type.Label("Data Set Requestor")
	private java.lang.String datasetRequestor;

	@org.kie.api.definition.type.Label("Requested Data Sets")
	private java.util.List<java.lang.String> requestedDatasets;

	public Request() {
	}

	public java.lang.String getGlobalClearenceNumber() {
		return this.globalClearenceNumber;
	}

	public void setGlobalClearenceNumber(java.lang.String globalClearenceNumber) {
		this.globalClearenceNumber = globalClearenceNumber;
	}

	public java.lang.String geteShareNumber() {
		return this.eShareNumber;
	}

	public void seteShareNumber(java.lang.String eShareNumber) {
		this.eShareNumber = eShareNumber;
	}

	public java.lang.String getAgreement_type() {
		return this.agreement_type;
	}

	public void setAgreement_type(java.lang.String agreement_type) {
		this.agreement_type = agreement_type;
	}

	public java.lang.String getDatasetRequestor() {
		return this.datasetRequestor;
	}

	public void setDatasetRequestor(java.lang.String datasetRequestor) {
		this.datasetRequestor = datasetRequestor;
	}

	public java.util.List<java.lang.String> getRequestedDatasets() {
		return this.requestedDatasets;
	}

	public void setRequestedDatasets(
			java.util.List<java.lang.String> requestedDatasets) {
		this.requestedDatasets = requestedDatasets;
	}

	public java.lang.Float getBudget_requested() {
		return this.budget_requested;
	}

	public void setBudget_requested(java.lang.Float budget_requested) {
		this.budget_requested = budget_requested;
	}

	public Request(java.lang.String globalClearenceNumber,
			java.lang.String eShareNumber, java.lang.String agreement_type,
			java.lang.Float budget_requested,
			java.lang.String datasetRequestor,
			java.util.List<java.lang.String> requestedDatasets) {
		this.globalClearenceNumber = globalClearenceNumber;
		this.eShareNumber = eShareNumber;
		this.agreement_type = agreement_type;
		this.budget_requested = budget_requested;
		this.datasetRequestor = datasetRequestor;
		this.requestedDatasets = requestedDatasets;
	}

}